/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Kalkulator;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.util.logging.*;
/**
 *
 * @author dewa
 */
public class Calculator extends javax.swing.JFrame {
    
    private static final Logger logger = Logger.getLogger(Calculator.class.getName());
    private JTextField display;
    private String operator = "";
    private double num1 = 0, num2 = 0, result = 0;
    
    
    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
        setTitle("Aplikasi Kalkulator");
        setSize(300, 400);
        setLayout(null);
        setLocationRelativeTo(null);

        display = new JTextField();
        display.setBounds(20, 20, 240, 40);
        display.setBackground(Color.PINK);
        display.setHorizontalAlignment(JTextField.RIGHT);
        display.setEditable(false);
        add(display);

        String[] tombol = {
            "7", "8", "9", "+",
            "4", "5", "6", "-",
            "1", "2", "3", "*",
            "0", "C", "B", "/",
            "%", "="
        };

        int x = 20, y = 80;
        for (String t : tombol) {
            JButton btn = new JButton(t);
            btn.setBounds(x, y, 50, 40);
            btn.addActionListener(this::aksiTombol);
            add(btn);
            x += 60;
            if (x > 200) {
                x = 20;
                y += 50;
            }
        }
    }

    private void aksiTombol(ActionEvent e) {
        String cmd = e.getActionCommand();

        if (cmd.matches("[0-9]")) {
            display.setText(display.getText() + cmd);
        } else if (cmd.matches("[+\\-*/%]")) {
            if (!display.getText().isEmpty()) {
                num1 = Double.parseDouble(display.getText());
                operator = cmd;
                display.setText("");
            }
        } else if (cmd.equals("=")) {
            if (!operator.isEmpty() && !display.getText().isEmpty()) {
                num2 = Double.parseDouble(display.getText());
                switch (operator) {
                    case "+" -> result = num1 + num2;
                    case "-" -> result = num1 - num2;
                    case "*" -> result = num1 * num2;
                    case "/" -> result = num1 / num2;
                    case "%" -> result = num1 % num2;
                }
                if (result % 1 == 0) {
                display.setText(String.valueOf((int) result));
                } else {
                display.setText(String.valueOf(result));
}

                operator = "";
            }
        } else if (cmd.equals("C")) {
            display.setText("");
            num1 = num2 = result = 0;
            operator = "";
        } else if (cmd.equals("B")) {
            String s = display.getText();
            if (s.length() > 0)
                display.setText(s.substring(0, s.length() - 1));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Calculator().setVisible(true));
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
